StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{59794EB1995D20F0}" {
   Id "A4D_Apple"
   Target_en_us "Apple"
   Target_fr_fr "Pomme"
   Modified 1502300953
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB6A81B77FA}" {
   Id "A4D_ATM"
   Target_en_us "ATM"
   Target_fr_fr "DAB"
   Modified 1501125556
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB4BBADF0E9}" {
   Id "A4D_Axe"
   Target_en_us "Axe"
   Target_fr_fr "Hache"
   Modified 1502300943
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E1E1A1AD1C5}" {
   Id "A4D_Bandage"
   Target_en_us "Bandage"
   Target_fr_fr "Bandage"
   Modified 1502303634
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB54A05E353}" {
   Id "A4D_Binocular"
   Target_en_us "Binocular"
   Target_fr_fr "Jumelle"
   Modified 1502300935
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597948244C18D946}" {
   Id "A4D_BuyAction"
   Target_en_us "Buy a"
   Target_fr_fr "Acheter un(e)"
   Modified 1501130019
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597948247B1FD77B}" {
   Id "A4D_BuyDescription"
   Target_en_us "You buy a"
   Target_fr_fr "Vous avez acheter un(e)"
   Modified 1501123440
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597948244ACF9299}" {
   Id "A4D_BuyTitle"
   Target_en_us "Shop"
   Target_fr_fr "Magasin"
   Modified 1501121619
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB624A2BC30}" {
   Id "A4D_Cannabis"
   Target_en_us "Cannabis"
   Target_fr_fr "Weed"
   Modified 1502301831
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB59A144E67}" {
   Id "A4D_Compass"
   Target_en_us "Compass"
   Target_fr_fr "Bousolle"
   Modified 1502301816
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E18769C1213}" {
   Id "A4D_CopperIngot"
   Target_en_us "Copper ingot"
   Target_fr_fr "Lingot de cuivre"
   Modified 1502302923
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E18BD0B89E2}" {
   Id "A4D_CopperUntreated"
   Target_en_us "Copper minerals"
   Target_fr_fr "Minerais de cuivre"
   Modified 1502303033
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB3044D9B9F}" {
   Id "A4D_Currency"
   Target_en_us "$"
   Target_fr_fr "€"
   Modified 1501123921
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB3E51C8B35}" {
   Id "A4D_EnergyDrink"
   Target_en_us "Energy drink"
   Target_fr_fr "Boisson energisante"
   Modified 1502301854
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597AC196D8976B12}" {
   Id "A4D_Flip"
   Target_en_us "Flip vehicle"
   Target_fr_fr "Retourner le véhicule"
   Modified 1501217543
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597948270AD47536}" {
   Id "A4D_For"
   Target_en_us "for"
   Target_fr_fr "pour"
   Modified 1501121510
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A683B61C4A}" {
   Id "A4D_FoundryDescriptionInUse"
   Target_en_us "The foundry is already in use by another person."
   Target_fr_fr "La fonderie est déjà utilisé par une autre personne."
   Modified 1501171998
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A7931932D8}" {
   Id "A4D_FoundryDescriptionOpen"
   Target_en_us "Foundry inventory and process are under development. thank you for being patient <3"
   Target_fr_fr "L'inventaire et le processus de fonderie sont en cours de développement. merci d'être patient <3"
   Modified 1501172600
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A75B7D1864}" {
   Id "A4D_FoundryDescriptionRelease"
   Target_en_us "The foundry no longer belongs to you."
   Target_fr_fr "La fonderie ne vous appartient plus."
   Modified 1501172407
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A70004F506}" {
   Id "A4D_FoundryDescriptionStart"
   Target_en_us "The foundry is active do not open it while it is working."
   Target_fr_fr "La fonderie est active ne l'ouvrez pas pendant qu'elle fonctionne."
   Modified 1501172236
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A73C207226}" {
   Id "A4D_FoundryDescriptionStartFailed"
   Target_en_us "Foundry failed to start."
   Target_fr_fr "La fonderie n'a pas pu démarrer."
   Modified 1501172111
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A68CA3681B}" {
   Id "A4D_FoundryDescriptionUse"
   Target_en_us "You can use this foundry. When you're done don't forget to release it. this may block you if you don't release."
   Target_fr_fr "Vous pouvez utiliser cette fonderie. Lorsque vous avez terminé, n'oubliez pas de le relâcher. cela peut vous bloquer si vous ne la relâchez pas."
   Modified 1501171910
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A6CF5B10C8}" {
   Id "A4D_FoundryOpenAction"
   Target_en_us "Open foundry inventory"
   Target_fr_fr "Ouvrir l'inventaire de la fonderie"
   Modified 1501172470
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A6DF9777C4}" {
   Id "A4D_FoundryReleaseAction"
   Target_en_us "Stop using this foundry"
   Target_fr_fr "Ne plus utiliser cette fonderie"
   Modified 1501342129
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A6AA725DDB}" {
   Id "A4D_FoundryStartAction"
   Target_en_us "Start foundry"
   Target_fr_fr "Démarrer la fonderie"
   Modified 1501172063
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A6918324D1}" {
   Id "A4D_FoundryTitle"
   Target_en_us "Foundry"
   Target_fr_fr "Fonderie"
   Modified 1501171782
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A6B07EC0BD}" {
   Id "A4D_FoundryUseAction"
   Target_en_us "Use foundry"
   Target_fr_fr "Utiliser la fonderie"
   Modified 1501171743
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59855B1EAFDB5B45}" {
   Id "A4D_GameDescription"
   Target_en_us "arma4dev.com develop this RPG game mode for you"\
   "</br>"\
   "we wanted to build an advanced framework leaving you free to create the most beautiful role play scenarios"\
   ""\
   "we are progressing well for the moment the project is not yet open source but we are working to make it soon"\
   ""\
   "we already have projects to put in place for a version 2, version 1 will not really add realistic animation for harvesting and other advanced features but this one will already allow you to create a role play experience for your players leaving us thus the time to better prepare the vesion 2"
   Target_fr_fr "arma4dev.com développe ce mode de jeu RPG pour vous. </br>Nous avons voulu construire un framework avancé vous laissant libre de créer les plus beaux scénarios de jeu de rôle</br>Nous avançons bien pour le moment le projet n'est pas encore open source mais nous travaillons pour le faire prochainement</br> Nous avons déjà des projets à mettre en place pour une version 2, la version 1 n'ajoutera pas vraiment d'animation réaliste pour la récolte et d'autres fonctionnalités avancées mais celle-ci vous permettra déjà de créer une expérience de jeu de rôle pour vos joueurs nous laissant ainsi le temps de mieux préparer la version 2."
   Modified 1502301521
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794824387E3170}" {
   Id "A4D_GatherAction"
   Target_en_us "Gather"
   Target_fr_fr "Ramasser"
   Modified 1501122919
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597948241FD297DC}" {
   Id "A4D_GatherDecription"
   Target_en_us "You gather"
   Target_fr_fr "Vous avez ramasser"
   Modified 1501123152
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{5972B5E4444A8429}" {
   Id "A4D_GatherTitle"
   Target_en_us "Gather"
   Target_fr_fr "Ramassage"
   Modified 1501132066
   Author "Zomb"
   LastChanged "Zomb"
   Labels {
    0
   }
  }
  CustomStringTableItem "{598B3E18E70FB48B}" {
   Id "A4D_IronIngot"
   Target_en_us "Iron ingot"
   Target_fr_fr "Lingot de fer"
   Modified 1502303195
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E1958E4CCDD}" {
   Id "A4D_IronUntreated"
   Target_en_us "Iron minerals"
   Target_fr_fr "Minerais de fer"
   Modified 1502303345
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E19F5A8C41F}" {
   Id "A4D_Light"
   Target_en_us "Light"
   Target_fr_fr "Lampe"
   Modified 1502303604
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB522ED2AD7}" {
   Id "A4D_Map"
   Target_en_us "Map"
   Target_fr_fr "Carte"
   Modified 1502300915
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962A1C5E1DCB1}" {
   Id "A4D_NothingToSell"
   Target_en_us "You have nothing to sell"
   Target_fr_fr "Vous n'avez rien à vendre"
   Modified 1501168866
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E0349947FEB}" {
   Id "A4D_Open"
   Target_en_us "Open"
   Target_fr_fr "Ouvrir"
   Modified 1502306335
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB4A1170782}" {
   Id "A4D_Pickaxe"
   Target_en_us "Pickaxe"
   Target_fr_fr "Pioche"
   Modified 1502300887
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB1966EF2A5}" {
   Id "A4D_Pizza"
   Target_en_us "Pizza"
   Target_fr_fr "Pizza"
   Modified 1502300876
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB66B2E5327}" {
   Id "A4D_Sand"
   Target_en_us "Sand"
   Target_fr_fr "Sable"
   Modified 1502300866
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E19B0984AE1}" {
   Id "A4D_SandUntreated"
   Target_en_us "Sand"
   Target_fr_fr "Sable"
   Modified 1502303481
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962B5D23E2F4E}" {
   Id "A4D_SellAction"
   Target_en_us "Seel"
   Target_fr_fr "Vendre"
   Modified 1501132014
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962BCD9C27D63}" {
   Id "A4D_SellActionNot"
   Target_en_us "You don't have"
   Target_fr_fr "Vous n'avez pas de"
   Modified 1501134038
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962B5E7FE8281}" {
   Id "A4D_SellDescription"
   Target_en_us "You sold"
   Target_fr_fr "Vous avez vendue"
   Modified 1501130113
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962B607694A9A}" {
   Id "A4D_SellTitle"
   Target_en_us "Trader"
   Target_fr_fr "Vendeur"
   Modified 1501130182
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB4FB29C997}" {
   Id "A4D_Shovel"
   Target_en_us "Shovel"
   Target_fr_fr "Pelle"
   Modified 1502300843
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{597962BDE60AD6FA}" {
   Id "A4D_ToSell"
   Target_en_us "to sell"
   Target_fr_fr "à vendre"
   Modified 1501134018
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E03B92B687D}" {
   Id "A4D_Vehicle"
   Target_en_us "Vehicle"
   Target_fr_fr "Vehicule"
   Modified 1502306470
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E03E28ECCDF}" {
   Id "A4D_VehicleLocked"
   Target_en_us "Your vehicle is now locked."
   Target_fr_fr "Votre véhicule est vérouiller."
   Modified 1502306635
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E001427FCE0}" {
   Id "A4D_VehicleLockUnlock"
   Target_en_us "Lock / Unlock"
   Target_fr_fr "Vérouiller / Déverouiller"
   Modified 1502306674
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E004EC73FED}" {
   Id "A4D_VehicleSpawn"
   Target_en_us "Your vehicle is ready and locked."
   Target_fr_fr "Votre véhicule est prêt et verouiller."
   Modified 1502306820
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E03A6A583F6}" {
   Id "A4D_VehicleUnlocked"
   Target_en_us "Your vehicle is unloked."
   Target_fr_fr "Votre véhicule est déverouiller."
   Modified 1502306586
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB57662BF89}" {
   Id "A4D_Watch"
   Target_en_us "Watch"
   Target_fr_fr "Montre"
   Modified 1502300833
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{59794EB387DA37F2}" {
   Id "A4D_Water"
   Target_en_us "Water bottle"
   Target_fr_fr "Bouteille d'eau"
   Modified 1502300824
   Author "Zomb"
   LastChanged "Zomb"
  }
  CustomStringTableItem "{598B3E18275BBA73}" {
   Id "A4D_WeedUntreated"
   Target_en_us "Weed untreated"
   Target_fr_fr "Weed non traité"
   Modified 1502302834
   Author "Zomb"
   LastChanged "Zomb"
  }
 }
}